"""Build one consolidated Markdown report covering noise, blur, and broken-image
results for both golden datasets (testsrc synthetic + Big Buck Bunny).

This is a reporting utility only -- it does not implement any metric/algorithm,
it just reads the CSVs already produced by run_pipeline.py and
compare_broken_samples.py and renders them into a single REPORT.md.

Usage:
    uv run python scripts/build_report.py
    uv run python scripts/build_report.py --output REPORT.md
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path


def _read_csv(path: Path) -> list[dict]:
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def _fmt(value: str, digits: int = 4) -> str:
    if value in (None, ""):
        return "—"
    try:
        return f"{float(value):.{digits}f}"
    except ValueError:
        return value


def _sweep_table(rows: list[dict], kind: str) -> str:
    lines = [
        "| Target PSNR | Actual PSNR | SSIM | MS-SSIM | VMAF |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        if r["type"] != kind:
            continue
        lines.append(
            f"| {_fmt(r['target_psnr'], 1)} | {_fmt(r['psnr'], 3)} | "
            f"{_fmt(r['ssim'])} | {_fmt(r['ms_ssim'])} | {_fmt(r['vmaf'], 2)} |"
        )
    return "\n".join(lines)


def _anchor_table(rows: list[dict]) -> str:
    lines = [
        "| Anchor | PSNR | SSIM | MS-SSIM | VMAF |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        if not r["type"].startswith("anchor_"):
            continue
        name = r["type"].replace("anchor_", "")
        lines.append(f"| {name} | {_fmt(r['psnr'], 3)} | {_fmt(r['ssim'])} | {_fmt(r['ms_ssim'])} | {_fmt(r['vmaf'], 2)} |")
    return "\n".join(lines)


def _broken_table(rows: list[dict]) -> str:
    lines = [
        "| Corruption type | PSNR | SSIM | MS-SSIM | VMAF |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda r: float(r["psnr"])):
        lines.append(
            f"| {r['pattern']} | {_fmt(r['psnr'], 3)} | {_fmt(r['ssim'])} | "
            f"{_fmt(r['ms_ssim'])} | {_fmt(r['vmaf'], 2)} |"
        )
    return "\n".join(lines)


def _vmaf80_crossover(rows: list[dict], kind: str) -> str:
    """Find the lowest target PSNR at which VMAF is still >= 80 for a given kind."""
    candidates = [
        r for r in rows
        if r["type"] == kind and r["vmaf"] not in (None, "") and float(r["vmaf"]) >= 80
    ]
    if not candidates:
        return "never reached in 15-30dB range"
    lowest = min(candidates, key=lambda r: float(r["target_psnr"]))
    return lowest["target_psnr"]


def build_section(name: str, outdir: Path) -> list[str]:
    metrics_rows = _read_csv(outdir / "metrics.csv")
    broken_rows = _read_csv(outdir / "broken" / "broken_metrics.csv")

    lines = [f"\n## {name}\n"]
    lines.append(f"\nGolden: `{outdir}/golden.png`\n")

    lines.append("\n### Gaussian Noise sweep (30.0 -> 15.0 dB)\n\n")
    lines.append(_sweep_table(metrics_rows, "noise"))

    lines.append("\n\n### Gaussian Blur sweep (30.0 -> 15.0 dB)\n\n")
    lines.append(_sweep_table(metrics_rows, "blur"))

    lines.append("\n\n### Extreme anchors (solid black / solid white)\n\n")
    lines.append(_anchor_table(metrics_rows))

    lines.append("\n\n### Broken-image / transcode-corruption samples (derived from golden, single comparison)\n\n")
    lines.append(_broken_table(broken_rows))

    noise_crossover = _vmaf80_crossover(metrics_rows, "noise")
    blur_crossover = _vmaf80_crossover(metrics_rows, "blur")
    lines.append("\n\n### Quick takeaway\n")
    lines.append(f"\n- Noise stays \"acceptable\" (VMAF >= 80) down to about **{noise_crossover} dB**.")
    lines.append(f"\n- Blur stays \"acceptable\" (VMAF >= 80) down to about **{blur_crossover} dB**.")
    lines.append("\n")
    return lines


def build_report(output_path: str) -> None:
    root = Path(__file__).resolve().parent.parent
    lines = [
        "# PSNR / SSIM / MS-SSIM / VMAF Full Report\n",
        "\nGenerated by `scripts/build_report.py` from the CSVs produced by "
        "`run_pipeline.py` (noise + blur sweeps, 30.0 -> 15.0 dB, 1.0 dB step) "
        "and `compare_broken_samples.py` (golden-derived transcode-corruption "
        "samples: block glitch, packet loss, row tearing, heavy compression, "
        "chroma loss/swap). All computation is pure OpenCV (no ffmpeg).\n",
    ]

    lines += build_section("Dataset A: Synthetic testsrc golden", root / "output")
    lines += build_section("Dataset B: Big Buck Bunny golden", root / "output_bbb")
    lines += build_section("Dataset C: Synthetic testsrc golden (4K/UHD, 3840x2160)", root / "output_4k")

    lines.append("\n## Cross-dataset comparison summary\n")
    lines.append(
        "\n| Dataset | Noise: last PSNR with VMAF>=80 | Blur: last PSNR with VMAF>=80 | "
        "Broken sample with lowest PSNR | Broken sample with highest VMAF |"
    )
    lines.append("\n|---|---|---|---|---|")
    for name, outdir in (("testsrc", root / "output"), ("Big Buck Bunny", root / "output_bbb"), ("testsrc 4K", root / "output_4k")):
        metrics_rows = _read_csv(outdir / "metrics.csv")
        broken_rows = _read_csv(outdir / "broken" / "broken_metrics.csv")
        noise_crossover = _vmaf80_crossover(metrics_rows, "noise")
        blur_crossover = _vmaf80_crossover(metrics_rows, "blur")
        lowest_psnr = min(broken_rows, key=lambda r: float(r["psnr"]))
        highest_vmaf = max(broken_rows, key=lambda r: float(r["vmaf"]) if r["vmaf"] not in (None, "") else -1)
        lines.append(
            f"\n| {name} | {noise_crossover} | {blur_crossover} | "
            f"{lowest_psnr['pattern']} ({_fmt(lowest_psnr['psnr'], 2)} dB) | "
            f"{highest_vmaf['pattern']} ({_fmt(highest_vmaf['vmaf'], 2)}) |"
        )
    lines.append("\n")

    lines.append("\n## Resolution comparison: 1920x1080 vs 3840x2160 (same synthetic testsrc content)\n")
    lines.append(
        "\nBoth datasets share the same procedurally-generated pattern (color bars, "
        "gradient, shapes/text), scaled to 1080p and 4K respectively, and are put "
        "through the identical noise/blur PSNR-calibrated sweep and transcode-"
        "corruption set. Since noise/blur are calibrated to hit the *same target "
        "PSNR* at both resolutions, this isolates how resolution alone shifts the "
        "perceptual (SSIM/VMAF) reading of an equal-PSNR distortion.\n"
    )
    res_rows_1080 = _read_csv(root / "output" / "metrics.csv")
    res_rows_4k = _read_csv(root / "output_4k" / "metrics.csv")
    lines.append(
        "\n| Target PSNR | Kind | SSIM (1080p) | SSIM (4K) | VMAF (1080p) | VMAF (4K) |"
    )
    lines.append("\n|---|---|---|---|---|---|")
    by_key_4k = {(r["type"], r["target_psnr"]): r for r in res_rows_4k}
    for r in res_rows_1080:
        if r["type"] not in ("noise", "blur"):
            continue
        if r["target_psnr"] not in ("30.0", "25.0", "20.0", "15.0"):
            continue
        r4k = by_key_4k.get((r["type"], r["target_psnr"]))
        if not r4k:
            continue
        lines.append(
            f"\n| {r['target_psnr']} | {r['type']} | {_fmt(r['ssim'])} | {_fmt(r4k['ssim'])} | "
            f"{_fmt(r['vmaf'], 2)} | {_fmt(r4k['vmaf'], 2)} |"
        )
    lines.append("\n")

    broken_1080 = {r["pattern"]: r for r in _read_csv(root / "output" / "broken" / "broken_metrics.csv")}
    broken_4k = {r["pattern"]: r for r in _read_csv(root / "output_4k" / "broken" / "broken_metrics.csv")}
    lines.append("\n| Corruption type | PSNR (1080p) | PSNR (4K) | VMAF (1080p) | VMAF (4K) |")
    lines.append("\n|---|---|---|---|---|")
    for pattern in broken_1080:
        b1080, b4k = broken_1080[pattern], broken_4k.get(pattern)
        if not b4k:
            continue
        lines.append(
            f"\n| {pattern} | {_fmt(b1080['psnr'], 2)} | {_fmt(b4k['psnr'], 2)} | "
            f"{_fmt(b1080['vmaf'], 2)} | {_fmt(b4k['vmaf'], 2)} |"
        )
    lines.append(
        "\n\n**Observation**: at matched target PSNR, VMAF direction depends on the "
        "distortion type. For noise, VMAF at 4K is close to (slightly below) "
        "1080p. For blur, VMAF drops noticeably more at 4K than at 1080p (e.g. "
        "target PSNR 30 dB: VMAF 56.19 at 1080p vs 43.79 at 4K) -- the same "
        "Gaussian blur sigma calibrated to a fixed PSNR removes proportionally "
        "more fine detail relative to a 4K frame's higher native sharpness "
        "expectation, so VMAF (which models perceived sharpness loss) penalizes "
        "it harder. For the golden-derived transcode corruptions, VMAF is "
        "consistently a few points *higher* at 4K for the same corruption "
        "(block_glitch, heavy_compression, chroma_swap), since a fixed-size "
        "corrupted region/JPEG block covers a smaller relative fraction of a "
        "larger 4K frame. PSNR/SSIM stay close between resolutions in both "
        "cases since those metrics operate on relative/local pixel neighborhoods "
        "rather than absolute pixel counts, unlike VMAF's resolution-aware "
        "perceptual model.\n"
    )

    lines.append("\n## Cross-validation: ffmpeg CLI vs OpenCV\n")
    lines.append(
        "\nTo make sure the pure-OpenCV metric implementations used everywhere "
        "in this report are trustworthy, `scripts/compare_ffmpeg_vs_opencv.py` "
        "independently recomputes PSNR/SSIM with ffmpeg's native `psnr`/`ssim` "
        "CLI filters (system `ffmpeg`, no libvmaf support on this machine) and "
        "compares MS-SSIM/VMAF against the standalone libvmaf binary. "
        "Full per-sample tables: "
        "[`output/ffmpeg_vs_opencv.md`](output/ffmpeg_vs_opencv.md), "
        "[`output_bbb/ffmpeg_vs_opencv.md`](output_bbb/ffmpeg_vs_opencv.md).\n"
    )
    lines.append(
        "\n| Dataset | Samples | PSNR WARN (>0.5dB delta) | SSIM WARN (>0.05 delta) | "
        "MS-SSIM WARN (>0.05 delta) | Max ΔPSNR | Max ΔSSIM |"
    )
    lines.append("\n|---|---|---|---|---|---|---|")
    for name, outdir in (("testsrc", root / "output"), ("Big Buck Bunny", root / "output_bbb")):
        val_rows = _read_csv(outdir / "ffmpeg_vs_opencv.csv")
        if not val_rows:
            continue
        psnr_warn = sum(1 for r in val_rows if r["psnr_flag"] == "WARN")
        ssim_warn = sum(1 for r in val_rows if r["ssim_flag"] == "WARN")
        msssim_warn = sum(1 for r in val_rows if r["msssim_flag"] == "WARN")
        psnr_deltas = [float(r["psnr_delta"]) for r in val_rows if r["psnr_delta"] not in (None, "")]
        ssim_deltas = [float(r["ssim_delta"]) for r in val_rows if r["ssim_delta"] not in (None, "")]
        max_psnr_d = max(psnr_deltas) if psnr_deltas else 0.0
        max_ssim_d = max(ssim_deltas) if ssim_deltas else 0.0
        lines.append(
            f"\n| {name} | {len(val_rows)} | {psnr_warn}/{len(val_rows)} | "
            f"{ssim_warn}/{len(val_rows)} | {msssim_warn}/{len(val_rows)} | "
            f"{max_psnr_d:.3f} dB | {max_ssim_d:.4f} |"
        )
    lines.append(
        "\n\n**Conclusion**: PSNR is numerically identical between OpenCV "
        "(`cv2.PSNR`) and ffmpeg (`-lavfi psnr`) on every sample tested (same "
        "MSE-based formula). SSIM agrees within ~0.01-0.05 (different default "
        "window: OpenCV's 11x11 Gaussian vs ffmpeg's 8x8 uniform -- both are "
        "valid SSIM variants). MS-SSIM shows the largest divergence from "
        "libvmaf's `float_ms_ssim`, especially on solid-color anchors and "
        "chroma-only corruption -- treat MS-SSIM as directionally useful but "
        "not numerically interchangeable across implementations. VMAF has no "
        "independent second implementation to diff against here.\n"
    )

    lines.append(
        "\n## Key findings\n"
        "\n1. **Same PSNR != same perceived quality.** At PSNR ~20 dB, noise "
        "still scores VMAF ~65-69 while blur is floored at VMAF 0 on both "
        "datasets -- PSNR alone cannot distinguish these two very "
        "differently-perceived distortions.\n"
        "\n2. **Blur is far more damaging per-dB than noise.** Blur rarely "
        "or never reaches VMAF>=80 even at PSNR 30 dB, while noise stays "
        "acceptable down to roughly PSNR 24-26 dB.\n"
        "\n3. **Color-only corruption (chroma_loss / chroma_swap) breaks the "
        "opposite way**: PSNR is very low (7-17 dB, looks catastrophic to a "
        "PSNR-only gate) yet VMAF is very high (92-97), because VMAF's model "
        "weighs luma far more than chroma. A human viewer would immediately "
        "notice a grayscale or color-cast frame, but VMAF would rate it as "
        "near-perfect.\n"
        "\n4. **Structural corruption (row tearing, block glitch, packet "
        "loss) is scored more consistently across metrics** -- both PSNR and "
        "VMAF agree these are visibly bad, though the exact severity ranking "
        "differs (e.g. row_tearing scores worst on VMAF despite not having "
        "the lowest PSNR of the broken set).\n"
        "\n5. **Practical implication**: no single metric is safe to use "
        "alone as an automated quality gate across arbitrary distortion "
        "types. A combination of PSNR (cheap, consistent trend) + SSIM/"
        "MS-SSIM (structural) + VMAF (perceptual, luma-heavy) gives a much "
        "more complete picture, and color-integrity should probably be "
        "checked separately (e.g. mean chroma delta) since none of these "
        "three metrics reliably flags pure color-cast/desaturation issues.\n"
    )

    Path(output_path).write_text("".join(lines))
    print(f"Wrote: {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a consolidated Markdown report (noise+blur+broken, both datasets).")
    parser.add_argument("--output", default=None, help="Output path (default: <psnr_toolkit>/REPORT.md)")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    output_path = args.output or str(root / "REPORT.md")
    build_report(output_path)


if __name__ == "__main__":
    main()
